source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

workspace 'ViperSample'

target 'ViperSample' do

  target 'ViperSampleTests' do
    pod 'SnapshotTesting', '1.9.0'
    pod 'TestUtils', :path => '../TestUtils'
  end

end
