#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

#==================================================================================================
name: ViperSample
#==================================================================================================

settings:
  MARKETING_VERSION: "0.0.1"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  defaultConfig: Release
  xcodeVersion: "13.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"

configs:
  Debug: debug
  Release: release
  Components: debug

#==================================================================================================
targets:
#==================================================================================================

#____________________________________________________________
# ViperSample

  ViperSample:

    platform: iOS
    type: application

    sources:
      - path: ViperSample

    #postBuildScripts:
    #- script: "${PODS_ROOT}/SwiftLint/swiftlint"
    #  name: SwiftLint

    settings:
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: "A9VWLHHDRZ"
      PRODUCT_BUNDLE_IDENTIFIER: br.com.ViperSample
      INFOPLIST_FILE: ViperSample/Info.plist

      ENABLE_BITCODE: "YES"
      TARGETED_DEVICE_FAMILY: "1"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
      ARCHS: "$(ARCHS_STANDARD)"

#____________________________________________________________
# Tests

  ViperSampleTests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - path: ViperSampleTests
        excludes:
          - "**/__Snapshots__"

    dependencies:
      - target: ViperSample

#==================================================================================================
schemes:
#==================================================================================================

  ViperSample:
    build:
      targets:
        ViperSample: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - ViperSample
      targets:
        - ViperSampleTests

#==================================================================================================
