#!/bin/bash

# Script path
scriptPath="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
projectName=$1

# Helper funcs
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#check if a received path exists, if it doesn't show error and stop script
foundPath() {
	pathToCheck="$1"
	if [ -d  $pathToCheck ]; then
		true
	else
		echo "Couldn't find path: $pathToCheck" && exit 0
		false
	fi
}

# Go to root
goToMainPath() {
    cd $scriptPath
    cd ..
}

# remove files
removeCurrentFiles() {
    find ./ -name "*.DS_Store" -exec rm -rf {} \;
    find ./ -name "*.lock" -exec rm -rf {} \;
    find ./ -name "*.xcodeproj" -exec rm -rf {} \;
    find ./ -name "*.xcworkspace" -exec rm -rf {} \;
    find ./ -name "Pods" -exec rm -rf {} \;
    find ./ -name "*.entitlements" -exec rm -rf {} \;
}

# pod install
podInstall() {
    bundle exec pod install
}

# create project
createProject() {
    local projectName=$1
    goToMainPath
    cd $projectName
    echo .
    echo ==================================================================
    echo Preparing "$projectName" workspace
    echo "Project path: $PWD"
    echo ==================================================================
    echo .
    xcodegen generate
    echo .
    echo ==================================================================
    echo "$projectName" Pod Install
    echo ==================================================================
    echo .
    podInstall
    echo .
    echo ==================================================================
    echo "$projectName".xcworkspace created
    echo ==================================================================
    echo .
}

createAppProject() {
    local projectName=$1
    goToMainPath

    cd App/$projectName
    echo .
    echo ==================================================================
    echo Preparing "$projectName" workspace
    echo "Project path: $PWD"
    echo ==================================================================
    echo .
    # Xcodegen for framework
    xcodegen generate
    echo .
    echo ==================================================================
    echo "$projectName" Pod Install
    echo ==================================================================
    echo .
    podInstall
    echo .
    echo ==================================================================
    echo "$projectName".xcworkspace created
    echo ==================================================================
    echo .
}

prepareWorkspaceFiles() {
    local projectName=$1
    pathToResourcesFolder="Resources/Assets"

    echo .
    echo ==================================
    echo "Prepare Workspace Files"
    echo "projectName: $projectName"
    echo ==================================
    echo .

    if foundPath $pathToResourcesFolder; then

        echo Searching target config files
		cd $pathToResourcesFolder

        echo Seting Gemfile file
		find ./ -name "Gemfile" -exec cp -R {} ../../$projectName \;
    fi

    goToMainPath
}

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Start setup
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# Script for sync templates, generate projects and install dependencies.
echo .
echo ==================================
echo Starting setup
echo "Script path: $scriptPath"
echo ==================================
echo .

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Remove current project files
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
echo .
echo ==================================================================
echo Removing current project files
echo ==================================================================
echo .
goToMainPath

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# # Create Projects
# #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#prepareWorkspaceFiles $projectName

cd $projectName
removeCurrentFiles
createProject $projectName
